# coding: utf-8
# @email: jinfeng.xu0605@gmail.com / jinfeng@connect.hku.hk

embedding_size: 64
feat_embed_dim: 64
n_layers: [1, 2, 3]
dropout: [0.1, 0.2, 0.3, 0.4, 0.5]
aggr_mode: 'add'
reg_weight: [0.0001, 0.001, 0.01, 0.1]
learning_rate: 0.001
batch_size: 1024
num_epoch: 1000

hyper_parameters: ["reg_weight", "dropout", "n_layers"]
