# coding: utf-8
# @email: jinfeng.xu0605@gmail.com / jinfeng@connect.hku.hk

embedding_size: 64
k: [40]
aggr_mode: 'mean'
construction: 'weighted_sum'
drop_rate: 0.1
reg_weight: [0.1, 0.01, 0.001, 0.0001, 0.00001]

hyper_parameters: ["k", "reg_weight"]
