# coding: utf-8
# @email: jinfeng.xu0605@gmail.com / jinfeng@connect.hku.hk

USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
TIME_FIELD: timestamp

inter_splitting_label: x_label

inter_file_name: 'tiktok.inter'
field_separator: "\t"
